import type { FC, ReactNode } from 'react';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Footer from './components/footer';
import Header from './components/header';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Cine verse',
  description: 'Generated by create next app',
};

interface Props {
  children: ReactNode;
}

const RootLayout: FC<Props> = ({
  children,
}) => {
  return (
    <html lang="en">
      <body className='flex flex-col w-screen h-screen items-cente overflow-hidden bg-neutral-900' style={inter.style}>
        <Header />
        <div className='flex flex-1 justify-center w-full p-10 overflow-y-auto'>
          <div className='flex flex-1 w-full max-w-screen-2xl'>
            {children}
          </div>
        </div>
        <Footer />
      </body>
    </html>
  );
};

export default RootLayout;
